version: '3.9'
services:
  postrges:
    container_name: ibook_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "IBook"
      POSTGRES_USER: "Ibook_user"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - db

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "nikitafedorov0904@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - db

  redis:
    image: redis:latest
    container_name: ibook_redis
    environment: 
      REDIS_PASSWORD: "1234"
      REDIS_USER: "ibook_user"
      REDIS_USER_PASSWORD: "1234"
    ports:
      - "6380:6379"
    depends_on:
      - "postrges"
    restart: unless-stopped
    networks:
      - db
networks:
  db:
    driver: bridge